; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
boards_dir = boards
src_dir = src

[env]
lib_deps =
	https://github.com/gonzomir/NMEAParser#parse-multiple-gnss
	https://github.com/moononournation/Arduino_GFX
	lvgl/lvgl@^8

[env:tft]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB
build_flags =
	-D LV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue

[env:rlcd]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
upload_protocol = esptool
upload_speed = 921600
monitor_speed = 115200
board_build.partitions = huge_app.csv
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 4MB
build_flags =
	-D LV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-D BOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
